version: '3.8'
services:
  frontend:
    build:
      context: ./testAng
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - exam

  backend:
    build:
      context: ./examserver
      dockerfile: Dockerfile
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/{DatabaseName}
      - spring.datasource.username={DatabaseUsername}
      - spring.datasource.password={DatabasePassword}
    ports:
      - 8080:8080
    networks:
      - exam

  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - exam

networks:
  exam:
    name: exam
